### ISSUE TITLE
Exploratory Data Analysis (Pandas)

### ISSUE THREAD

**Issue by Shazy021** [Shazy021/EDA_tdata#1]
Провести разведочный анализ полученных данных.

- [x] Проверить данные таблицы products:
- Валидация данных
- Заполнение пропусков

- [x]  Проверить данные таблицы buyers:
- Освоить geopandas, keplergl
- Визуализация geo Points

**Comment by QuDevE** [comment]
Folium - удалось отобразить только 30к маркеров из 1 млн гео точек (Даже с использованием кластеров удалось отобразить максимум 150к маркеров);
Keplergl - проблемы с установкой на linux (стоит попробовать на windows).

Удалось отобразить 1 млн гео точек на `basemap` из `mpl_toolkits`:


![Image](https://github.com/Shazy021/EDA_tdata/assets/92948703/e733a151-60b8-4be3-a11f-689f0cf42e79)


Чек-лист:
- [x]  - EDA;
- [x] - Валидация данных;
- [x] - Обновление данных в таблице products;
- [x] - Т.к. не настроено каскадное удаление, то удалить из orders данные о покупке пользователей (с пропусками) из таблицы buyers;
- [x] - Удаление данных  о пользователях без гео меток (Таблица: buyers).
