### ISSUE TITLE
EDA orders table (spark)

### ISSUE THREAD

**Issue by Shazy021** [Shazy021/EDA_tdata#2]
- [x] - Spark db connection
- [x] - EDA orders table
- [x] - Create day/month/year metrics with other db table

For metrics you can use spark and pandas.

**Comment by QuDevE** [comment]
При помощи одного лишь pandas у нас не получится вытащить данные из таблицы orders т.к в ней находится ~5 млн. записей.

- [x] - Load table from db;
- [x] - first check;
- [x] - optimization;
- [x] - create new columns place and region;

---
Заметки:
- Нехватка памяти
- После распаковки array (item_ids) обрабатываем ~72 млн записей

![Image](https://github.com/Shazy021/EDA_tdata/assets/92948703/8aab0b1e-a5f0-4510-bd6f-cfdc23fca07c)
---

**Comment by QuDevE** [comment]
Характеристики устройства:
OS: arch linux
Cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Mem: PC300 NVMe SK hynix 256GB

**Comment by Shazy021** [comment]
# geocoder osm

* Не был выбран т.к. скорость обработки 1it/s;
* Платные решения не рассматривались;

# geopy Nominatim

* Не был выбран т.к. скорость обработки максимум до 2it/s;
* Платные решения не рассматривались;
---
# Reverse Geocoder

* Быстрое офлайн решение на основе K-D tree;

![Image](https://github.com/Shazy021/EDA_tdata/assets/79043866/4f3fdd0d-a923-4bda-8f77-c5c64ffb7f92)

**Comment by QuDevE** [comment]
Вывод до 20к гео-точек покупателей с которых наибольшая выручка за определенный период:

- [x] - Добавить к маркерам popup;
- [x] - Использовать folium clusters;
- [x] - Cохранение карты в формате png;
- [x] - Отображение из markdown сохраненных карт в png после вызова ф-ций (для гитхаба, т.к github не отображает folium map)

![Image](https://github.com/Shazy021/EDA_tdata/assets/92948703/a53bf43d-c054-4de5-9bfc-a7fd1570fcba)
